alias be='bundle exec'
alias rs='bundle exec rails s -b=0.0.0.0'
alias rc='bundle exec rails c'
alias rr='bundle exec rails routes'
alias bi='bundle install'
alias sinatra='bundle exec ruby app.rb -o0.0.0.0'
