require('plugins.plugin')
require('plugins.lsp')
require('plugins.scheme')
require('plugins.status_line')
require('plugins.filer')
require('plugins.git')
require('plugins.terminal')
require('plugins.insx')
