#                                                ####
#                                                  ##
#                                                  ##
#                                                  ##
#               ############        ######  ##     ##  ######      ######  ####          ######  ##
#               ##      ##        ##      ####     ####      ##        ####    ##      ##      ####
#                     ##          ##        ##     ##        ##        ##      ##    ##          ##
#                     ##          ##               ##        ##        ##            ##
#                   ##              ########       ##        ##        ##            ##
#                   ##                      ##     ##        ##        ##            ##
#     ##          ##      ##    ##          ##     ##        ##        ##            ##          ##
#   ######      ##        ##    ####        ##     ##        ##        ##              ##        ##
#   ######    ##############    ##  ########     ######    ######  ############          ########
#     ##

# zsh profile用
if [ "$ZSHRC_PROFILE" != "" ]; then
  zmodload zsh/zprof && zprof > /dev/null
fi

# === zsh.d のファイル読み込み ===
ZSHD_HOME="${HOME}/.dotfiles/zsh/zsh.d"
for config_file ($ZSHD_HOME/*.zsh(N)) source $config_file

# === fzfの設定 ===
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# === extensionのファイル読み込み ===
EXTENSION_HOME="${HOME}/.dotfiles/zsh/extension"
for config_file ($EXTENSION_HOME/*.zsh(N)) source $config_file

# === functionのファイル読み込み ===
FUNCTION_HOME="${HOME}/.dotfiles/zsh/function"
for config_file ($FUNCTION_HOME/*.zsh(N)) source $config_file
